<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;

/**
 * PageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageContentRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByLangAndPageWithoutReturningThem($locale, Page $page)
	{
		$qb = $this->createQueryBuilder('pc');

		$qb
			->select('pc.varname, pc.content')
			->where('pc.page = :page')->setParameter('page', $page)
			->andWhere('pc.locale = :locale')->setParameter('locale', $locale)
		;
		
		return $qb
			->getQuery()
			->getResult()
		;
	}
}
